name: water_jug_riddle
description: Water Jug Riddle Solving Application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.4
  intl: ^0.17.0
  flutter_riverpod: ^1.0.3
  flutter_svg: ^1.0.3
  align_positioned: ^3.0.0
  flutter_modular: ^4.4.0
  url_strategy: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: baloo
      fonts:
        - asset: assets/fonts/baloo2_regular.ttf
          weight: 400
        - asset: assets/fonts/baloo2_medium.ttf
          weight: 500
        - asset: assets/fonts/baloo2_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/baloo2_bold.ttf
          weight: 700
        - asset: assets/fonts/baloo2_extra_bold.ttf
          weight: 800